In [29]:
import numpy as np
np.warnings.filterwarnings('ignore', category=np.VisibleDeprecationWarning)

In [30]:
lst = [1,2,3, 4]
myarray = np.array(lst)

In [31]:
myarray

array([1, 2, 3, 4])

In [32]:
lst2 = [11,22,33,44]

In [33]:
mylst = [lst, lst2]

In [37]:
mylst

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [35]:
arr2 = np.array(mylst)

In [36]:
arr2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [46]:
arr2.shape
#np.shape(arr2)

(2, 4)

In [40]:
arr2.dtype

dtype('int64')

In [58]:
a = np.zeros(5)

In [44]:
a.dtype

dtype('float64')

In [47]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [50]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [53]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [60]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])