In [1]:
import numpy as np

In [2]:
#Numpy Data types:
#Numerical Data Types: Integers (int), Unsigned integers(uint), floating point(float), complex
#Other Data Types: booleans(bool), string, datetime, Python object

In [3]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [4]:
print(a)

[2 3 4]


In [5]:
#arange() is a np function
a = np.arange(1,12,2)
a

array([ 1,  3,  5,  7,  9, 11])

In [6]:
print(a)

[ 1  3  5  7  9 11]


In [7]:
#linspace is a linear space function of np. This creates a floating array
#linspace(start, stop, total # of elements)
a = np.linspace(1,12,6)
a

array([ 1. ,  3.2,  5.4,  7.6,  9.8, 12. ])

In [8]:
a.reshape(3,2)

array([[ 1. ,  3.2],
       [ 5.4,  7.6],
       [ 9.8, 12. ]])

In [9]:
a

array([ 1. ,  3.2,  5.4,  7.6,  9.8, 12. ])

In [10]:
a = a.reshape(3,2)

In [11]:
a

array([[ 1. ,  3.2],
       [ 5.4,  7.6],
       [ 9.8, 12. ]])

In [12]:
a.size
#size do not care about the shape of the array, it just says the total number of elements in the array
#size is not a fucntion, so dont need parenthesis.

6

In [13]:
a.shape #shape is not a function, so dont need parenthesis 

(3, 2)

In [14]:
a.dtype

dtype('float64')

In [15]:
a.itemsize

8

In [17]:
b = np.array([(1,5,2,3),(4,5,6, 7)])

In [18]:
b

array([[1, 5, 2, 3],
       [4, 5, 6, 7]])

In [19]:
a < 4

array([[ True,  True],
       [False, False],
       [False, False]])

In [20]:
 a *=3

In [21]:
a

array([[ 3. ,  9.6],
       [16.2, 22.8],
       [29.4, 36. ]])

In [22]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
a.dtype

dtype('float64')

In [24]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
a = np.ones(10)

In [26]:
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
a = np.array([2,3,4],dtype = np.int16)

In [31]:
a

array([2, 3, 4], dtype=int16)

In [32]:
a.dtype

dtype('int16')

In [33]:
a.itemsize

2

In [34]:
a = np.random.random((2,3))

In [35]:
a

array([[0.91657389, 0.71866949, 0.02019415],
       [0.21691423, 0.67702159, 0.39633818]])

In [36]:
np.set_printoptions(precision =2, suppress=True)

In [37]:
a

array([[0.92, 0.72, 0.02],
       [0.22, 0.68, 0.4 ]])

In [38]:
a = np.random.randint(0,10,5)
#random.randint - for raandom integers.
#this gives 0 to 10 inclusive with 5 total numbers.

In [39]:
a

array([5, 9, 4, 6, 5])

In [40]:
a.sum()

29

In [41]:
a.min()

4

In [43]:
a.max()

9

In [44]:
a.mean()

5.8

In [45]:
a.var()

2.96

In [46]:
a.std()

1.7204650534085253

In [47]:
a = np.random.randint(1,10,6)

In [48]:
a

array([1, 6, 9, 5, 4, 3])

In [51]:
a = a.reshape(3,2)

In [52]:
a

array([[1, 6],
       [9, 5],
       [4, 3]])

In [53]:
#sum of only axis 1
a.sum(axis =1)

array([ 7, 14,  7])

In [54]:
a.sum(axis =0)

array([14, 14])

In [ ]:
#to load data from a text file
#data = np.loadtxt('data.txt',dtype=np.uint8,delimiter =',', skiprows =1)
#this loadtxt() do not accept exceptions very well. If there are any missing values or characters mixed. It cant handle
#instead genfromtxt - handles exceptions a lot better

In [55]:
a = np.arange(10)

In [56]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.random.shuffle(a)

In [58]:
a

array([0, 1, 9, 4, 7, 8, 3, 6, 2, 5])